dist: xenial
sudo: false
language: python
cache: pip
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install requests-mock
  - pip install coveralls
script:
  - coverage run --source=getnet -m unittest discover
after_success:
  - coveralls

matrix:
  include:
  - name: "Black"
    python: 3.7
    install: travis_retry pip install black
    script: black --check .
    after_success: skip
